[[GAP_pkg_browse]]
arch = "aarch64"
git-tree-sha1 = "7f6ca94d9c022385f92b8d5b37aa34fe65505252"
os = "macos"

    [[GAP_pkg_browse.download]]
    sha256 = "fe375ceed0ac3e133315dcd507ba4aa72da4f11685bcee9ab60ac07773cae29d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82100.0+0/GAP_pkg_browse.v101.82100.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_browse]]
arch = "aarch64"
git-tree-sha1 = "4b55b4193c23a9ac6b5819a659cc6053d254239d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "a66940142c96d258ac94cf4c579ec68ba79cd6d8ea8506c387fe3b85f2e2da60"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82100.0+0/GAP_pkg_browse.v101.82100.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_browse]]
arch = "aarch64"
git-tree-sha1 = "cc3e3ff1846005f106bf95b3970ac85e1f403b57"
libc = "musl"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "9d109a2743d2e8a7ca0c078dab0da02273de875adde3da8b63c808257e8e40d0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82100.0+0/GAP_pkg_browse.v101.82100.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_browse]]
arch = "aarch64"
git-tree-sha1 = "990d8c831f87f1487e20900cb08582dd2d8e2f64"
os = "freebsd"

    [[GAP_pkg_browse.download]]
    sha256 = "f9772e36dd6074865b3aca92e0bb80554c8133ae565971f527b8cb81a06a1c68"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82100.0+0/GAP_pkg_browse.v101.82100.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_browse]]
arch = "powerpc64le"
git-tree-sha1 = "f2dc67d54ef397e2d39775fe2712c1d45dd482e9"
libc = "glibc"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "a1d5b841def7f544f0474584d9463d957e29204979c0e9082e71e7c3f56653e1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82100.0+0/GAP_pkg_browse.v101.82100.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_browse]]
arch = "riscv64"
git-tree-sha1 = "260818e06e174c44616f8063ba178846fbdb008d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "8c328b40794545a4d2e08729e8e59105de147736906811f0f5381eee806acfe3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82100.0+0/GAP_pkg_browse.v101.82100.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_browse]]
arch = "x86_64"
git-tree-sha1 = "ccc1a8b82772c061cb730a489595a9421a1e71b4"
os = "macos"

    [[GAP_pkg_browse.download]]
    sha256 = "37a5e37067dddc9d10d6638b68339fd5d6c0e219705ce5623494f608e6fde9dc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82100.0+0/GAP_pkg_browse.v101.82100.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_browse]]
arch = "x86_64"
git-tree-sha1 = "00c684fecb327b7fb58cb90fb1721c11a5244cfe"
libc = "glibc"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "5dca71d197f291b7b47a9a497df835ebbb10d39dfd1af635681e704b0fd94aa3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82100.0+0/GAP_pkg_browse.v101.82100.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_browse]]
arch = "x86_64"
git-tree-sha1 = "2f4b04bea36e040382026063070c3234046dd657"
libc = "musl"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "c7bb1efd61d070f967f9a9188a1517a9ff1bc474e68e51a3d38f39e488e7d8a3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82100.0+0/GAP_pkg_browse.v101.82100.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_browse]]
arch = "x86_64"
git-tree-sha1 = "7531d9944d3507ed8504142afd87f91e47c373cb"
os = "freebsd"

    [[GAP_pkg_browse.download]]
    sha256 = "616e323202fd03618a79124028df7633d5f08336d1a72e5e361a718ec3e3f90b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82100.0+0/GAP_pkg_browse.v101.82100.0.x86_64-unknown-freebsd.tar.gz"
