name = "GAP_pkg_browse_jll"
uuid = "6e540885-1cbc-538c-85e7-b800ca60d645"
version = "101.82100.1+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Ncurses_jll = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
GAP_jll = "5cd7a574-2c56-5be2-91dc-c8bc375b9ddf"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.10"
Ncurses_jll = "6.5.1"
Libdl = "< 0.0.1, 1"
GAP_jll = "~400.1500.0"
Artifacts = "< 0.0.1, 1"
